### PR TITLE
chore: Enable support for `extends`

### LINKED ISSUE #2: Look into `extends` functionality
yargs processes this for nyc, babel-plugin-istanbul will be left out.  If `extends` can be processed here it should, otherwise babel plugin will have to document that it's not supported.  Maybe see if yargs is willing to split the extends processing to a separate/single-purpose module so it can be used from here?

### PR DESCRIPTION
**Pull request by coreyfarrell**
Fixes #2

### CODE REVIEW

**Comment by coreyfarrell** [comment]
This actually provides greater capability than yargs itself.

1. extends can point to a yaml file
2. extends are properly resolved from the location of the file where the extends is found
3. extends can be an array of strings

Might be worth contributing 2 and 3 back to yargs.  yargs doesn't already require yaml so I don't think it's reasonable to include that.

This may cause some "breakage" if people have invalid `extends`.  Specifically if a path cannot be resolved or is not a string we throw, yargs only throws if an include loop is found.

One other really obscure breakage might be possible occur.  If someone has an extends pattern matching `..*rc$` which matches a local file and a module name, this will find the module instead of the local file.  I'm guessing it's rare for a module name to contain a `.` and end in `rc`.

**Comment by bcoe** [comment]
there's enough logic happening here that my preference would be to try to consolidate it in a module that yargs vendors...

any thoughts on how we might do this and still keep `yaml` support? I'd like to avoid adding a yaml parser to yargs for the time being.

**Comment by coreyfarrell** [comment]
Maybe an option somewhere for custom loaders?
```js
const loadYML = file => require('js-yaml').load(fs.readFileSync(file, 'utf8'));

yargs
  .customConfigLoader('.yaml', loadYML)
  .customConfigLoader('.yml', loadYML)
```

apply-extends needs the ability to load a specific filename, maybe that's the functionality that should be in the module?  Granted we could just use `applyExtends(cwd, {extends: 'config-we-found.yml'})` to load the main configuration file.

FWIW I'm against yargs vendoring the functionality if we create a module for it.  Vendoring a dependency doesn't make it go away, it just means nyc would install and load two copies of the same code.  As far as yargs dependencies, you know we're down to 25 in 13.3.0, was twice that in 13.2.4 (the os-locale change).  Vendoring the os-locale code was different in that doing so had a functional purpose, eliminating a huge number of dependencies.

**Comment by coreyfarrell** [comment]
This PR is blocking other stuff, I'm going to merge since nobody has raised issues with the public API nor the way this works.  I'm not ready to do a final release of this module yet but I will need to publish an alpha version soon.  Nothing stops us from moving code around after that happens.

**Pull request merged**
